# Pressa development commands. Run `just ci` before finishing any task.

default:
    @just --list

fmt:
    cargo fmt --all

# Enable the repo's git hooks (pre-commit formats staged Rust files).
hooks:
    git config core.hooksPath .githooks

lint:
    cargo clippy --workspace --all-targets -- -D warnings

test:
    cargo test --workspace

check:
    cargo check --workspace --all-targets

# Everything CI runs. Must be green before a task is done.
ci:
    cargo fmt --all --check
    cargo clippy --workspace --all-targets -- -D warnings
    cargo test --workspace

# Review snapshot diffs deliberately. Never `insta accept` blindly.
snap:
    cargo insta review

# Open the example project.
run:
    cargo run -p pressa-tui -- dev --project examples/blog

validate:
    cargo run -p pressa-tui -- validate --project examples/blog

# Throwaway projects in /tmp for driving the CLI by hand (wipes and rebuilds).
sandbox:
    #!/usr/bin/env bash
    set -euo pipefail
    repo="{{ justfile_directory() }}"
    sandbox=/tmp/pressa-sandbox

    rm -rf "$sandbox"
    mkdir -p "$sandbox"/{empty,blog,posts,broken,deep/a/b/c}

    # A wrapper rather than a copy of the binary: it rebuilds first, so the
    # sandbox always runs the working copy rather than yesterday's build.
    cat > "$sandbox/pressa" <<SH
    #!/bin/sh
    cargo build --quiet --manifest-path "$repo/Cargo.toml" -p pressa-tui || exit \$?
    exec "$repo/target/debug/pressa" "\$@"
    SH
    chmod +x "$sandbox/pressa"

    # The good schema is the example itself, so the sandbox cannot drift from it.
    cp "$repo/examples/blog/pressa.yaml" "$sandbox/blog/pressa.yaml"
    cp "$repo/examples/blog/pressa.yaml" "$sandbox/deep/pressa.yaml"

    # `posts/` is the same schema with one line changed: `list_columns` widened
    # so every cell renderer is on screen at once. The fields stay
    # single-sourced from the example, so only the line being demonstrated can
    # drift. `sed` to a new file rather than `-i`, which differs on BSD and GNU.
    sed 's/^    list_columns: .*/    list_columns: [title, status, views, featured, published_at, metadata]/' \
        "$repo/examples/blog/pressa.yaml" > "$sandbox/posts/pressa.yaml"

    cat > "$sandbox/broken/pressa.yaml" <<'YAML'
    project:
      name: broken

    collections:
      posts:
        fields:
          - name: title
            type: text
          - name: slug
            type: text
          - name: status
            type: text
          - name: author
            type: relation      # not an M0 type: `validate` names this path
    YAML

    cat > "$sandbox/README.md" <<'MD'
    # pressa sandbox

    Generated by `just sandbox` — never edit it here, edit the recipe in the
    repository's `justfile`. `just sandbox` wipes and regenerates this directory.

    `./pressa` builds the working copy and runs it, so it is never a stale binary.
    For a shorter command: `export PATH=/tmp/pressa-sandbox:$PATH`

    | Directory | Holds | For |
    |---|---|---|
    | `empty/` | nothing | `init` from scratch |
    | `blog/` | a copy of `examples/blog/pressa.yaml`, no records | `validate`, `dev`, the empty list, the record editor, the log, `data.db` |
    | `posts/` | the same schema, wider `list_columns`, 20 records | the table: every cell renderer, scrolling, `g`/`G`, `r` |
    | `broken/` | a schema with `type: relation` | an error naming the YAML path |
    | `deep/` | `pressa.yaml` at the top, empty `a/b/c` | discovery walking up, the way git finds `.git` |

    ## Try

        cd /tmp/pressa-sandbox
        ./pressa --help                       # three subcommands
        ./pressa init --project empty         # writes empty/pressa.yaml and empty/.pressa/
        ./pressa validate --project empty     # schema ok: 1 collection, 8 fields
        ./pressa init --project empty         # refuses, exit 1, touches nothing

        cd blog
        ../pressa validate                    # one line on stdout, exit 0
        ../pressa dev                         # opens the TUI; q gives the shell back, exit 0
        ../pressa dev > /dev/null             # not a terminal: exit 1, "could not be prepared"
        ls -a .pressa                         # data.db appears only after `dev`
        cat .pressa/pressa.log                # started / resolved / services ready / tui started

        cd ../broken && ../pressa validate    # exit 1: collections.posts.fields[3].type ...
        cd ../deep/a/b/c && ../../../../pressa validate   # finds the project in deep/

    ## The list view

    Two directories, two halves of T8.

    `blog/` has the schema and no records, so `Enter` on `Posts` draws the
    header row and then says why the body is empty:

        ┌ pressa › Posts ──────────────────────────────── 0 records ───┐
        │ Collections   │  TITLE           STATUS          VIEWS      │
        │               │ ──────────────────────────────────────────  │
        │ > Posts       │                                             │
        │               │   No records yet.  Press n to create the    │
        │               │   first one.                                │

    `posts/` is the same schema with one line changed — `list_columns` widened
    to every field the table can draw — and twenty records in it:

        cd posts && ../pressa dev

        ┌ pressa › Posts ─────────────────────────────────────────────────────────────────── 20 records ───┐
        ├────────────────────┬─────────────────────────────────────────────────────────────────────────────┤
        │ Collections        │  TITLE           STATUS      VIEWS    FEATURED  PUBLISHED AT       METADATA │
        │                    │ ─────────────────────────────────────────────────────────────────────────── │
        │ > Posts            │ ▸Hello world     draft       1        ✓         2026-09-02 01:01   {2}      │
        │                    │  About page      published   4        ·         2026-09-03 02:02   {2}      │
        │                    │  Release notes   draft       —        ·         —                  —        │
        │                    │  Title 04        published   16       ·         2026-09-05 04:04   {2}      │

    Six columns want about 100 of them. At 80 they all still fit, because every
    column keeps at least six characters and the rest ends in `…`:

        │ Collections        │  TITLE       STATUS   VIEWS   FEATU…  PUBLISHE…  METAD… │
        │ > Posts            │ ▸Hello wor…  draft    1       ✓       2026-09-…  {2}    │

    That is the rule, not a defect: nothing is clipped silently. A cell too
    wide for its column ends in `…`, and a column that cannot have its six
    characters is dropped and counted — `+3` at the end of the header row.

    What the frames are showing:

    | Thing | Where it comes from |
    |---|---|
    | The columns, and their order | `list_columns` in `pressa.yaml` — this is the only line `posts/pressa.yaml` changes |
    | The header text | each field's `label`, uppercased |
    | `20 records` | the records that loaded; absent from the title when the load failed |
    | `▸` and the reversed row | the selection |
    | `—` | a field this record has no value for |
    | `✓` / `·` | a `boolean`, true / false |
    | `2026-09-02 01:01` | a `datetime`: the stored RFC 3339 string's first 16 characters, never a relative time |
    | `{2}` | a `json` object, and how many keys it has |
    | `↓ 6 more` | records below the panel — scroll down to see them |

    Keys in the list: `j`/`k` or `↑`/`↓` move, `g`/`G` jump to the ends,
    `Ctrl+D`/`Ctrl+U` move by ten, `r` reloads, `Enter` edits the selected
    record, `n` creates one, and `Esc`/`h`/`←`/`q` goes back. The hint bar
    shows `↑↓ Navigate   Enter Edit   n New   Esc Back`; `?` lists the rest once
    T11 builds the help overlay.

    ## The record editor

    T9 closes the loop: a record typed in `dev` is still there after a restart.

        cd blog && ../pressa dev
        # Enter on Posts, then n          a blank form, Title focused
        # Ctrl+S                          refused: three "⚠ required", nothing saved
        # Enter, type, Enter              Title; Tab moves to the next field
        # Tab, Enter, type, Enter         Slug
        # Tab, Enter, Enter               Status: — then draft then published
        # Tab, Tab, Enter, 42, Enter      Views
        # Ctrl+S                          "Record saved.", back at the list, one row
        # q, q, ../pressa dev, Enter      the row is still there

    The form is generated from `pressa.yaml` like the table is — one block per
    field, in schema order:

        ┌ pressa › Posts › Hello world ───────────────────────── ● unsaved · Ctrl+S ───┐
        │ Collections        │  Title *                                                │
        │                    │    Hello world                                          │
        │ > Posts            │                                                         │
        │                    │  Slug *                                                 │
        │                    │    hello-world                                          │
        │                    │                                                         │
        │                    │  Status *        ‹ published ›                          │
        │                    │                                                         │
        │                    │  Content                                                │
        │                    │    —                                                    │
        │                    │                                                         │
        │                    │ ▸Views                                                  │
        │                    │    42                                                   │
        │                    │                                                         │
        │                    │  Featured        [ ]                                    │
        │                    │                                                         │
        │                    │  Published at                                 ↓ 1 more  │

    | Thing | What it means |
    |---|---|
    | `▸` and the reversed bar | the focused field — moving it moves nothing else |
    | `▌` in the box | you are typing; `Enter` keeps it, `Esc` throws it away |
    | `*` | required: a save without it is refused |
    | `‹ published ›` | a `select`; `Enter` or `l`/`h` cycles the options |
    | `[ ]` / `[x]` | a `boolean`; `Enter` or `Space` toggles it |
    | `● unsaved · Ctrl+S` | something was changed and not saved yet |
    | `⚠ …` under a field | why the last save, or the last commit, was refused |
    | `↓ 1 more` | fields below the panel — `Tab` scrolls to them |

    `Textarea` and `json` fields open a five-row box: `Enter` is a newline
    there, and `Tab` finishes the field. `Enter` on a row of the list opens that
    record — `posts/` has twenty to try it on. `Esc` on a form with unsaved
    changes asks `Discard unsaved changes?` first; `y` discards, `n` stays.

    ## Try changing the schema

    The table is generated from `pressa.yaml` and from nothing else, so this
    needs no rebuild of anything but the config:

        cd posts
        $EDITOR pressa.yaml      # reorder list_columns, or cut it to [title]
        ../pressa dev            # the table changed

    Add a field to `fields` and name it in `list_columns` and a column appears;
    rename a `label` and the header follows it. There is no per-collection code
    to edit — one renderer draws them all.

    The frames above are what this recipe printed when it was last changed.
    `just sandbox` regenerates the directories and reseeds `posts/`, so if what
    you see differs, the recipe is stale and that is a finding.

    ## Exit codes

        ./pressa validate --project blog; echo $?               # 0
        ./pressa dev --project blog > /dev/null; echo $?        # 1  every pressa error
        ./pressa --log-level nonsense validate; echo $?         # 2  clap's usage errors

    ## Log level

        rm -f blog/.pressa/pressa.log
        ./pressa --log-level error dev --project blog > /dev/null
        wc -c < blog/.pressa/pressa.log   # 0
        ./pressa dev --project blog > /dev/null
        wc -c < blog/.pressa/pressa.log   # > 0

    ## Start over

        just sandbox
    MD

    # Records, so that `dev` has a table to draw and not just a header row.
    # An example target and not a subcommand — see `pressa-tui/examples/seed.rs`.
    cargo run --quiet -p pressa-tui --example seed -- "$sandbox/posts" 20

    echo "sandbox ready: $sandbox (see its README.md)"
