# Pressa development commands. Run `just ci` before finishing any task.

default:
    @just --list

fmt:
    cargo fmt --all

# Enable the repo's git hooks (pre-commit formats staged Rust files).
hooks:
    git config core.hooksPath .githooks

lint:
    cargo clippy --workspace --all-targets -- -D warnings

test:
    cargo test --workspace

check:
    cargo check --workspace --all-targets

# Everything CI runs. Must be green before a task is done.
ci:
    cargo fmt --all --check
    cargo clippy --workspace --all-targets -- -D warnings
    cargo test --workspace

# Review snapshot diffs deliberately. Never `insta accept` blindly.
snap:
    cargo insta review

# Open the example project.
run:
    cargo run -p pressa-tui -- dev --project examples/blog

validate:
    cargo run -p pressa-tui -- validate --project examples/blog

# Throwaway projects in /tmp for driving the CLI by hand (wipes and rebuilds).
sandbox:
    #!/usr/bin/env bash
    set -euo pipefail
    repo="{{ justfile_directory() }}"
    sandbox=/tmp/pressa-sandbox

    rm -rf "$sandbox"
    mkdir -p "$sandbox"/{empty,blog,broken,deep/a/b/c}

    # A wrapper rather than a copy of the binary: it rebuilds first, so the
    # sandbox always runs the working copy rather than yesterday's build.
    cat > "$sandbox/pressa" <<SH
    #!/bin/sh
    cargo build --quiet --manifest-path "$repo/Cargo.toml" -p pressa-tui || exit \$?
    exec "$repo/target/debug/pressa" "\$@"
    SH
    chmod +x "$sandbox/pressa"

    # The good schema is the example itself, so the sandbox cannot drift from it.
    cp "$repo/examples/blog/pressa.yaml" "$sandbox/blog/pressa.yaml"
    cp "$repo/examples/blog/pressa.yaml" "$sandbox/deep/pressa.yaml"

    cat > "$sandbox/broken/pressa.yaml" <<'YAML'
    project:
      name: broken

    collections:
      posts:
        fields:
          - name: title
            type: text
          - name: slug
            type: text
          - name: status
            type: text
          - name: author
            type: relation      # not an M0 type: `validate` names this path
    YAML

    cat > "$sandbox/README.md" <<'MD'
    # pressa sandbox

    Generated by `just sandbox` — never edit it here, edit the recipe in the
    repository's `justfile`. `just sandbox` wipes and regenerates this directory.

    `./pressa` builds the working copy and runs it, so it is never a stale binary.
    For a shorter command: `export PATH=/tmp/pressa-sandbox:$PATH`

    | Directory | Holds | For |
    |---|---|---|
    | `empty/` | nothing | `init` from scratch |
    | `blog/` | a copy of `examples/blog/pressa.yaml` | `validate`, `dev`, the TUI, the log, `data.db` |
    | `broken/` | a schema with `type: relation` | an error naming the YAML path |
    | `deep/` | `pressa.yaml` at the top, empty `a/b/c` | discovery walking up, the way git finds `.git` |

    ## Try

        cd /tmp/pressa-sandbox
        ./pressa --help                       # three subcommands
        ./pressa init --project empty         # writes empty/pressa.yaml and empty/.pressa/
        ./pressa validate --project empty     # schema ok: 1 collection, 8 fields
        ./pressa init --project empty         # refuses, exit 1, touches nothing

        cd blog
        ../pressa validate                    # one line on stdout, exit 0
        ../pressa dev                         # opens the TUI; q gives the shell back, exit 0
        ../pressa dev > /dev/null             # not a terminal: exit 1, "could not be prepared"
        ls -a .pressa                         # data.db appears only after `dev`
        cat .pressa/pressa.log                # started / resolved / services ready / tui started

        cd ../broken && ../pressa validate    # exit 1: collections.posts.fields[3].type ...
        cd ../deep/a/b/c && ../../../../pressa validate   # finds the project in deep/

    ## The list view

    `Enter` on `Posts` loads the collection and draws its table; `Esc` comes
    back. A fresh `data.db` has no records in it, so what this sandbox shows
    you is the empty list — the header row, and why the body is empty:

        ┌ pressa › Posts ──────────────────────────────── 0 records ───┐
        │ Collections   │  TITLE           STATUS          VIEWS      │
        │               │ ──────────────────────────────────────────  │
        │ > Posts       │                                             │
        │               │   No records yet.                           │

    With records in it the same panel draws them, one row each, `▸` on the
    selection and the count in the title:

        ┌ pressa › Posts ──────────────────────────────── 3 records ───┐
        │ Collections   │  TITLE           STATUS          VIEWS      │
        │               │ ──────────────────────────────────────────  │
        │ > Posts       │ ▸Hello world     draft           0          │
        │               │  About page      published       42         │
        │               │  Release notes   draft           —          │

    **You cannot get to that second screen from this sandbox yet**: nothing in
    the product creates a record until the editor arrives in T9, and `dev` is
    the only command that opens the screen. Until then the populated table
    lives in the snapshots — `list_snapshots__frame_b_three_records.snap` and
    its eight neighbours in `pressa-tui/tests/snapshots/`, which is where both
    frames above come from. Read those rather than trusting these two, which
    are trimmed to fit this file.

    What the frames are showing:

    | Thing | Where it comes from |
    |---|---|
    | The columns, and their order | `list_columns` in `pressa.yaml` — edit it and the table changes, with no code change |
    | The header text | each field's `label`, uppercased |
    | `0 records` / `3 records` | the records that loaded; absent when the load failed |
    | `—` | a field the record has no value for |
    | `✓` / `·` | a `boolean` that is true / false |
    | `{3}` | a `json` object, and its key count |
    | `↓ 6 more` | records below the panel; nothing is hidden silently |

    Keys in the list: `j`/`k` or `↑`/`↓` move, `g`/`G` jump to the ends,
    `Ctrl+D`/`Ctrl+U` move by ten, `r` reloads, and `Esc`/`h`/`←`/`q` goes
    back. Only the first and last are in the hint bar; `?` lists the rest once
    T11 builds the help overlay.

    ## Exit codes

        ./pressa validate --project blog; echo $?               # 0
        ./pressa dev --project blog > /dev/null; echo $?        # 1  every pressa error
        ./pressa --log-level nonsense validate; echo $?         # 2  clap's usage errors

    ## Log level

        rm -f blog/.pressa/pressa.log
        ./pressa --log-level error dev --project blog > /dev/null
        wc -c < blog/.pressa/pressa.log   # 0
        ./pressa dev --project blog > /dev/null
        wc -c < blog/.pressa/pressa.log   # > 0

    ## Start over

        just sandbox
    MD

    echo "sandbox ready: $sandbox (see its README.md)"
